require:
  - rubocop-rake
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
  SuggestExtensions: false

Metrics/ModuleLength:
  Max: 200

Style/Documentation:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - "Rakefile"
    - "**/*.rake"
    - "test/**/*"

Metrics/ClassLength:
  Exclude:
    - "test/**/*"

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'test/**/*'
    - 'lib/migrations/tasks.rake'

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Naming/FileName:
  Exclude:
    - 'lib/migrations.rb' 