require:
  - rubocop-rake
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: true

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - '*.gemspec'
    - 'lib/migrations/tasks.rake'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'test/**/*'
    - 'lib/migrations/tasks.rake'

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Naming/FileName:
  Exclude:
    - 'lib/migrations.rb' 