name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rubocop:
    name: RuboCop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false
      - name: Configure Bundler
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle config set --local deployment false
      - name: Install dependencies
        run: bundle install
      - name: Run RuboCop
        run: bundle exec rubocop

  test:
    name: Ruby ${{ matrix.ruby }} + Rails ${{ matrix.rails }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Rails 6.1
          - ruby: '3.0'
            rails: '6.1.0'
          - ruby: '3.1'
            rails: '6.1.0'
          # Rails 7.0
          - ruby: '3.0'
            rails: '7.0.0'
          - ruby: '3.1'
            rails: '7.0.0'
          - ruby: '3.2'
            rails: '7.0.0'
          # Rails 7.1
          - ruby: '3.1'
            rails: '7.1.0'
          - ruby: '3.2'
            rails: '7.1.0'
          - ruby: '3.3'
            rails: '7.1.0'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false
      - name: Configure Bundler
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle config set --local deployment false
      - name: Install dependencies
        run: |
          bundle update rails --jobs 4 --retry 3
          bundle install
      - name: Run tests
        run: bundle exec rake test

  security:
    name: Security checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false
      - name: Configure Bundler
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle config set --local deployment false
      - name: Install dependencies
        run: |
          gem install bundler-audit
          bundle install
      - name: Check for vulnerable dependencies
        run: bundle audit check --update

  docs:
    name: Documentation coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false
      - name: Configure Bundler
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle config set --local deployment false
      - name: Install dependencies
        run: |
          gem install yard
          bundle install
      - name: Generate documentation
        run: yard doc --fail-on-warning 